const posts = [
  {
    id: "1",
    username: "faker",
    tag: "미드",
    content: "같이 할 정글 구합니다. 캐리해드려요",
    updatedTime: "2020-11-29",
  },
  {
    id: "2",
    username: "bang",
    tag: "원딜",
    content: "보조해줄 실력자 서폿 구합니다. 탱커 서폿 선호합니다.",
    updatedTime: "2020-11-28",
  },
  {
    id: "3",
    username: "wolf",
    tag: "서폿",
    content: "공격적인 원딜 구합니다. 성장형 원딜 사절",
    updatedTime: "2020-11-27",
  },
  {
    id: "4",
    username: "bengi",
    tag: "정글",
    content: "로밍형 미드라이너 구합니다. 확정 cc기 있는분들 선호",
    updatedTime: "2020-11-26",
  },
  {
    id: "5",
    username: "marin",
    tag: "탑",
    content: "같이 할 정글 구합니다. 역갱각 잘 잡는 분들로.",
    updatedTime: "2020-11-25",
  },
  {
    id: "6",
    username: "showmaker",
    tag: "미드",
    content: "같이 할 로밍형 서폿 구합니다.",
    updatedTime: "2020-11-24",
  },
  {
    id: "7",
    username: "faker",
    tag: "미드",
    content: "같이 할 정글 구합니다. 캐리해드려요",
    updatedTime: "2020-11-29",
  },
  {
    id: "8",
    username: "bang",
    tag: "원딜",
    content: "보조해줄 실력자 서폿 구합니다. 탱커 서폿 선호합니다.",
    updatedTime: "2020-11-28",
  },
  {
    id: "9",
    username: "wolf",
    tag: "서폿",
    content: "공격적인 원딜 구합니다. 성장형 원딜 사절",
    updatedTime: "2020-11-27",
  },
  {
    id: "10",
    username: "bengi",
    tag: "정글",
    content: "로밍형 미드라이너 구합니다. 확정 cc기 있는분들 선호",
    updatedTime: "2020-11-26",
  },
  {
    id: "11",
    username: "marin",
    tag: "탑",
    content: "같이 할 정글 구합니다. 역갱각 잘 잡는 분들로.",
    updatedTime: "2020-11-25",
  },
  {
    id: "12",
    username: "showmaker",
    tag: "미드",
    content: "같이 할 로밍형 서폿 구합니다.",
    updatedTime: "2020-11-24",
  },
];

export default posts;
